version: '2'
services:
  db1:
    container_name: mysql_db1
    image: mysql:5.6
    # command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'test'
    volumes:
      - ./mysql-data/db1:/var/lib/mysql
    ports:
      - 3307:3306
  db2:
    container_name: mysql_db2
    image: mysql:5.6
    # command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'test'
    volumes:
      - ./mysql-data/db2:/var/lib/mysql
    ports:
      - 3308:3306